# Generated by Django 5.0.7 on 2024-08-07 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='articles',
            new_name='article',
        ),
    ]
